name: 'Detect Pull Requests Conflicts'
description: 'Combine multiple labelled pull requests and detect conflicts between pull requests'
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'git-pull-request'
  color: 'red'
inputs:
  pull-request:
    description: 'Changed pull request for merge with another'
    required: true
    default: '0'
  label:
    description: 'The label to look for pull requests'
    required: false
    default: 'deploy.dev'
  label-conflict:
    description: 'The label to set for conflicted pull requests'
    required: false
    default: 'deploy.dev.conflict'
  author-name:
    description: 'The author name of the merge commit'
    required: false
    default: 'nobody'
  author-email:
    description: 'The author email of the merge commit'
    required: false
    default: 'nobody@nobody'
  repo-token:
    description: 'The GitHub token'
    required: true
    default: 'github.token'
runs:
  using: 'docker'
  image: 'dockerfile'
  env:
    PULL_REQUEST: ${{ inputs.pull-request }}
    PULL_REQUEST_LABEL: ${{ inputs.label }}
    PULL_REQUEST_LABEL_CONFLICT: ${{ inputs.label-conflict }}
    GITHUB_TOKEN: ${{ inputs.repo-token }}
    GIT_AUTHOR_NAME: ${{ inputs.author-name }}
    GIT_AUTHOR_EMAIL: ${{ inputs.author-email }}
